version: "3"
services:
  fast_api:
    build: 
      context: backend/
    depends_on:
      - mongo
      
    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env
    
    environment:
      - MONGODB_HOST_NAME = mongodb_database

  stream_lit:
    build:
      context: frontend/
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"

  mongodb_database: 
    image: mongo 

    volumes:
      - movie_recomm_database:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: localhost
      MONGO_INITDB_ROOT_PASSWORD: skapeed24!)97

volumes:
  movie_recomm_database: